name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            image-name: openstack-venv-builder-ubuntu
            from: ghcr.io/vexxhost/python-base-ubuntu:2023.2@sha256:68fbf3b6f4db2c7c00991967192d8b57f9dbf27b7a5b97a1b3ba142b76f2580f
          - name: ubuntu-cloud-archive
            image-name: openstack-venv-builder-ubuntu-cloud-archive
            from: ghcr.io/vexxhost/python-base-ubuntu-cloud-archive:2023.2@sha256:bfca5f45db9266b1ed3757c0d81d876c651e13cdb9979ebb70b961ccba065398
          - name: ubuntu-cloud-archive-legacy
            image-name: openstack-venv-builder
            from: ghcr.io/vexxhost/python-base:2023.2@sha256:80d4a6ad5cae940578c9876969f18e072398a25554ac23591101106a3908f158
          - name: debian
            image-name: openstack-venv-builder-debian
            from: ghcr.io/vexxhost/python-base-debian:2023.2@sha256:98d8d3eb102481a7e9692e3ef7039c07b6492247391aa499d46c331fed2b7a33
          - name: rockylinux
            image-name: openstack-venv-builder-rockylinux
            from: ghcr.io/vexxhost/python-base-rockylinux:2023.2@sha256:b71a7c5b77a79c10c0d3f0b321f09b4999944e1469e0e2ccdfc8cd1921822fea
          - name: almalinux
            image-name: openstack-venv-builder-almalinux
            from: ghcr.io/vexxhost/python-base-almalinux:2023.2@sha256:f39c91e3fa35599116007509433b576adbba47afd728848bdfae596b97764948
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@9dc904e06dcde958bf8a0b3230715d32b9e3a85f # main
        with:
          repository: openstack/requirements
          ref: 2023.2-eol

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@9dc904e06dcde958bf8a0b3230715d32b9e3a85f # main
        with:
          image-name: ${{ matrix.image-name }}
          build-contexts: requirements=openstack/requirements
          build-args: FROM=${{ matrix.from }}
          push: ${{ github.event_name != 'pull_request' }}
