name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            image-name: openstack-venv-builder-ubuntu
            from: ghcr.io/vexxhost/python-base-ubuntu:main@sha256:527dc220738323b83d53e53013044830027585a0e8e4b32f3fc3e7027d564dea
          - name: ubuntu-cloud-archive
            image-name: openstack-venv-builder-ubuntu-cloud-archive
            from: ghcr.io/vexxhost/python-base-ubuntu-cloud-archive:main@sha256:d549ba1e21dc01f9dd392401bf404fdab4f9aa17277a5cac66e4b823203e03e5
          - name: ubuntu-cloud-archive-legacy
            image-name: openstack-venv-builder
            from: ghcr.io/vexxhost/python-base:main@sha256:17f958037ba6a999ed3a4fd7f624313cd51718134c7bb404ac7c45f1a65e3c55
          - name: debian
            image-name: openstack-venv-builder-debian
            from: ghcr.io/vexxhost/python-base-debian:main@sha256:efc17d448b012dc5e4deb719a9d22d06266767b57aee431e2cf2ce48f9824dd9
          - name: rockylinux
            image-name: openstack-venv-builder-rockylinux
            from: ghcr.io/vexxhost/python-base-rockylinux:main@sha256:c227cc66255e9e89014cfe9a1caf8063cc4fd5bad951fc88af056417760fbc78
          - name: almalinux
            image-name: openstack-venv-builder-almalinux
            from: ghcr.io/vexxhost/python-base-almalinux:main@sha256:270067c689e43236cc1831bc44f59ea5537556565403edd124123b2565d9c674
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/requirements
          ref: f8a07e962c7b0b2f1839761042d3a35ae3c51c43 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          image-name: ${{ matrix.image-name }}
          build-contexts: requirements=openstack/requirements
          build-args: FROM=${{ matrix.from }}
          push: ${{ github.event_name != 'pull_request' }}
