name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            image-name: openstack-venv-builder-ubuntu
            from: ghcr.io/vexxhost/python-base-ubuntu:main@sha256:037646f91de40f53ca67f61fefd8de8e3b4a267c6ce38c3c3c81cc9bff61d77b
          - name: ubuntu-cloud-archive
            image-name: openstack-venv-builder-ubuntu-cloud-archive
            from: ghcr.io/vexxhost/python-base-ubuntu-cloud-archive:main@sha256:07f2ccce3c937e12db4a799065b201ce1bf6524bcc8bdf895abcdc5d531804c1
          - name: ubuntu-cloud-archive-legacy
            image-name: openstack-venv-builder
            from: ghcr.io/vexxhost/python-base:main@sha256:8079595da80f8292b290194d0a6833e479d8f37694778c0db2ef7f476e852cac
          - name: debian
            image-name: openstack-venv-builder-debian
            from: ghcr.io/vexxhost/python-base-debian:main@sha256:fb315e7d4ce6c13337ff479147b0c16c8aa312fd2d01f859d560c9766b7c4a5e
          - name: rockylinux
            image-name: openstack-venv-builder-rockylinux
            from: ghcr.io/vexxhost/python-base-rockylinux:main@sha256:3cf26a90e8b0d895a44f5947c49ead8c53e84f7ad384ad62173e06af9793b4e5
          - name: almalinux
            image-name: openstack-venv-builder-almalinux
            from: ghcr.io/vexxhost/python-base-almalinux:main@sha256:c1d77bb659e76f0e7d639f9989f50b1960be1063b779e2cc218ee6e60ccd94eb
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          repository: openstack/requirements
          ref: 2bd07c0208ec11b29bc2df2412b211cd2cb3df88 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          image-name: ${{ matrix.image-name }}
          build-contexts: requirements=openstack/requirements
          build-args: FROM=${{ matrix.from }}
          push: ${{ github.event_name != 'pull_request' }}
